# Generated by Django 4.1.2 on 2022-11-25 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_user_google_user_email_user_groups_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DummyUser",
        ),
    ]
