# Generated by Django 4.1.2 on 2022-11-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_delete_dummyuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
