# Generated by Django 4.1.2 on 2022-12-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_user_is_staff"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="userclub",
            constraint=models.UniqueConstraint(
                fields=("user", "club"), name="unique register"
            ),
        ),
    ]
