# Generated by Django 4.1.2 on 2022-12-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_userclub_unique_register"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.CharField(max_length=255),
        ),
    ]
