# Generated by Django 4.1.2 on 2022-11-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_participation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="type",
            field=models.CharField(
                choices=[
                    ("A", "Announcement"),
                    ("E", "Enrollment"),
                    ("S", "Scheduling"),
                ],
                max_length=1,
            ),
        ),
    ]
