name: Frontend CD

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install yarn
      run: npm install --global yarn

    - name: Install dependencies
      run: yarn install

    - name: Build
      run: yarn build
      env:
        NEXTAUTH_GOOGLE_CLIENT_ID: ${{ secrets.NEXTAUTH_GOOGLE_CLIENT_ID }}
        NEXTAUTH_GOOGLE_CLIENT_SECRET: ${{ secrets.NEXTAUTH_GOOGLE_CLIENT_SECRET }}
        NEXTAUTH_URL: https://${{ secrets.DOMAIN }}/
        NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
        NEXT_PUBLIC_BASE_URL: https://${{ secrets.HOST }}

    - uses: kersvers/s3-sync-with-cloudfront-invalidation@v1.0.0
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DISTRIBUTION_ID: ${{ secrets.AWS_DISTRIBUTION_ID }}
        AWS_REGION: 'ap-northeast-2'   # optional: defaults to us-east-1
        SOURCE_DIR: 'out'      # optional: defaults to entire repository