name: Test Coverage

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.4'

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install python dependencies
      working-directory: ./udong-backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install node dependencies
      working-directory: ./udong-frontend
      run: |
        yarn install

    - name: Test Frontend
      working-directory: ./udong-frontend
      run: |
        yarn test --coverage --watchAll=false

    - name: Test Backend
      working-directory: ./udong-backend/udong
      run: |
        coverage run --branch --source='.' --omit='udong/*,dummy.py' manage.py test
        coverage lcov
        coverage xml

    - name: Merge coverage
      run: |
        sed 's/^SF:/SF:udong-frontend\//g' udong-frontend/coverage/lcov.info > coverage.lcov
        sed 's/^SF:/SF:udong-backend\/udong\//g' udong-backend/udong/coverage.lcov >> coverage.lcov

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.lcov

    - name: Override Coverage Source Path for Sonar
      working-directory: ./udong-backend/udong
      run: sed -i 's/<source>\/home\/runner\/work\/swppfall2022-team1\/swppfall2022-team1\/udong-backend\/udong<\/source>/<source>\/github\/workspace\/udong-backend\/udong<\/source>/g' coverage.xml

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Remove Coveralls badge cache
      run: |
        curl -w "\n" -s -X PURGE https://coveralls.io/repos/github/swsnu/swppfall2022-team1/badge.svg\?branch\=main
