name: Test Coverage

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.4'

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install python dependencies
      working-directory: ./udong-backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install node dependencies
      working-directory: ./udong-frontend
      run: |
        yarn install

    - name: Test Frontend
      working-directory: ./udong-frontend
      run: |
        yarn test --coverage --watchAll=false

    - name: Test Backend
      working-directory: ./udong-backend/udong
      run: |
        coverage run --source='.' manage.py test
        coverage lcov

    - name: Merge coverage
      run: |
        sed 's/^SF:/SF:udong-frontend\//g' udong-frontend/coverage/lcov.info > coveralls.lcov
        sed 's/^SF:/SF:udong-backend\/udong\//g' udong-backend/udong/coverage.lcov >> coveralls.lcov

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coveralls.lcov

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
