# Generated by Django 4.1.2 on 2022-11-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timedata", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="time",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="time",
            name="end_time",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="time",
            name="start_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="time",
            name="start_time",
            field=models.IntegerField(null=True),
        ),
    ]
