# Generated by Django 4.1.2 on 2022-11-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timedata", "0002_alter_time_end_date_alter_time_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="time",
            name="end_time",
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="time",
            name="start_time",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
