# Generated by Django 4.1.2 on 2022-11-11 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
        ("timedata", "0003_alter_time_end_time_alter_time_start_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="time",
            name="scheduling",
        ),
        migrations.AlterField(
            model_name="time",
            name="event",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_set",
                to="event.event",
            ),
            preserve_default=False,
        ),
    ]
